### ISSUE TITLE
Prettier.nvim doesn't work

### ISSUE THREAD

**Issue by dlvhdr** [MunifTanjim/prettier.nvim#10] opened 2022-08-14 18:43 UTC
I've generated a vscode extension code with `yo` and saw prettier didn't work.
I tried adding a .prettierrc file, running `:Prettier` but nothing works.
It seems NullLs does run but simply doesn't write the file.
I tried also restarting prettierd.

### My configuration

Ignore all the helper functions I created as they are unused.

https://github.com/dlvhdr/dotfiles/blob/26266aef5cb4738c52f6c4c72d4326f794512dc1/.config/nvim/lua/dlvhdr/lsp/servers/null-ls.lua#L1

### `NullLsInfo`

![image](https://user-images.githubusercontent.com/6196971/184550270-823a8d3f-ad4e-48f4-ae47-8ab81eb54c54.png)

### `NullLsLog`

```
[TRACE Sun Aug 14 21:34:22 2022] .../site/pack/packer/start/null-ls.nvim/lua/null-ls/rpc.lua:121: received LSP request for method shutdown
[TRACE Sun Aug 14 21:34:22 2022] .../site/pack/packer/start/null-ls.nvim/lua/null-ls/rpc.lua:146: received LSP notification for method exit
```

### `LspInfo`
![image](https://user-images.githubusercontent.com/6196971/184550250-654ce834-784c-49b8-9932-f68ea2a494b2.png)

**Comment by dlvhdr** [comment] 2022-08-14 18:58
Seems to be working with prettier, but that's super slow.
Not sure why prettierd doesn't work...

**Comment by MunifTanjim** [comment] 2022-08-15 09:49
This should be fixed now. This was the root cause: https://github.com/fsouza/prettierd/issues/237

Prettier CLI options are not supported by `prettierd`. So for now, prettier options passed to `prettier.setup({})` won't be used with `prettierd`.

**Closed as completed** 2022-08-15 09:51 UTC
